### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by Jessicaward** [Jessicaward/SpotNetCore#25]
Queues entity with parameter of:

- Type (album, artist, track, playlist).
- Search query (e.g. Visions, Radiohead, Schism, This Is Bjork).

**Comment by Jessicaward** [comment]
Exception:

**Message**
The JSON value could not be converted to System.Collections.Generic.IEnumerable`1[SpotNetCore.Models.SpotifyTrack]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.

**Stack Trace**
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at SpotNetCore.Services.SearchService.SearchForTrack(String query) in //Services/SearchService.cs:line 41
   at SpotNetCore.Implementation.CommandHandler.HandleCommands() in //Implementation/CommandHandler.cs:line 144

**Comment by Jessicaward** [comment]
Fix for above issue here: https://stackoverflow.com/a/65659699/5151441

**Comment by Jessicaward** [comment]
Queueing now implemented here: #49
